//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hive.Presenter.ServiceClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceClient.HiveService")]
    public interface HiveService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HiveService/authenticate", ReplyAction="http://tempuri.org/HiveService/authenticateResponse")]
        Hive.Domain.User authenticate(Hive.Domain.User user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HiveServiceChannel : Hive.Presenter.ServiceClient.HiveService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HiveServiceClient : System.ServiceModel.ClientBase<Hive.Presenter.ServiceClient.HiveService>, Hive.Presenter.ServiceClient.HiveService {
        
        public HiveServiceClient() {
        }
        
        public HiveServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HiveServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HiveServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HiveServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Hive.Domain.User authenticate(Hive.Domain.User user) {
            return base.Channel.authenticate(user);
        }
    }
}
